# Generated by Django 3.2.12 on 2022-11-14 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_orders_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myshop.customers'),
        ),
    ]
