# Generated by Django 3.2.12 on 2022-11-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20221114_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='time',
        ),
    ]
