# Generated by Django 3.2.12 on 2022-11-15 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_remove_orders_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
