# Generated by Django 3.2.12 on 2022-11-15 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_orders_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
